### ISSUE TITLE
JSON scope highlighting

### ISSUE THREAD

**Issue by Saturate** [paradox41/material-color-scheme#20]
Syntax highlighting is not really useful when dealing with JSON, consider doing scope highlighting.
An example is [Neon-color-scheme](https://github.com/MattDMo/Neon-color-scheme), see below for a comparison.

Material color scheme:
![scope-highlighting-2](https://cloud.githubusercontent.com/assets/453018/6326030/bfdbfc32-bb4d-11e4-8b1f-a700f4f2759d.PNG)

Neon color scheme:
![scope-highlighting](https://cloud.githubusercontent.com/assets/453018/6326031/bfdcdb20-bb4d-11e4-8aea-fc1ff1b323bc.PNG)

**Comment by paradox41** [comment]
Should be easy enough. I'll look into it.

**Comment by Saturate** [comment]
Yeah, but a lot of color schemes are missing it. It seems like something that Sublime Text should do out of the box.

But thanks! :-)

**Comment by Saturate** [comment]
Awesome work, thanks!
