### ISSUE TITLE
Theme doesn't affect anything when selected on atom 0.184.0

### ISSUE THREAD

**Issue by Seth-Johnson** [paradox41/material-color-scheme#22]
When I apply the syntax theme on atom 0.184.0 my file's syntax reverts to the backgrund color of my UI theme (I'm using atom-dark currently).

For example, in a python file this is what I see:  

![test2 py - -home-seth - atom_014](https://cloud.githubusercontent.com/assets/3377752/6432390/b3ea1722-c004-11e4-847b-f5d281083e6d.png)  

I've tried different languages including HTML, C++ , Javascript, and, of course, Python. I get no syntax highlighting whatsoever. 

Atom doesn't report any errors.

**Comment by Seth-Johnson** [comment]
Oh, atom reports the theme's version at 2.1.0

**Comment by paradox41** [comment]
Odd, I'll take a look.

**Comment by saschaeggi** [comment]
Still the same issue with Version 2.1.1

**Comment by paradox41** [comment]
Thanks. 2.1.1 was not intended to fix the atom issues. I am not sure what is going on, I'll have to look around.

**Comment by saschaeggi** [comment]
Found a solution. I just added a index.less file in the root folder of your theme (material folder) with the following content:

@import "./atom/material-dark/styles/base.less";

Works (at least as a workaround).

**Comment by paradox41** [comment]
Wow! I removed that thinking it wasn't actually doing anything. Goes to show...

Fixed in 2.1.2 via 2398305a3b64bc59e051fec965437eed0d9f45d4

**Comment by saschaeggi** [comment]
V 2.1.3 works again

**Comment by paradox41** [comment]
Thanks for finding the fix @saschaeggi
