### ISSUE TITLE
Atom Usage?

### ISSUE THREAD

**Issue by ericclemmons** [paradox41/material-color-scheme#24]
How do you switch to "light" mode in Atom?  I can't figure it out.

Markdown isn't so great in dark mode :)

> 
![screen shot 2015-06-16 at 6 52 59 pm](https://cloud.githubusercontent.com/assets/15182/8197053/f6047352-1458-11e5-9b0d-9dac77e1bc10.png)

**Comment by paradox41** [comment]
Atom doesn't currently support multiple schemes in one repo, so you are stuck with dark unless you are willing to make some alterations to the code.

If you open up [index.less](https://github.com/paradox41/material-color-scheme/blob/master/index.less#L1) and change that line, you can get access to light.

**Comment by ericclemmons** [comment]
Thanks!

**Comment by paradox41** [comment]
Not a problem. Sorry it isn't easier. Once Atom adds support for multiple schemes per repo, I'll make the changes needed so you won't have to do this. :D
