### ISSUE TITLE
cant activate in atom

### ISSUE THREAD

**Issue by apansky** [paradox41/material-color-scheme#30]
Hey man, 

i installed theme, but i cant activate it, i dont see it in my list of themes. Do you any have idea what the problem might be?

Thanx !

**Comment by shimion96** [comment]
The problem isn't that the theme isn't installed but, checking the UI and Syntax theme. The new theme will be amongst the list, or scroll down for the different category of themes that you have installed

**Comment by willsoto** [comment]
Yup. It's a color scheme, not a ui theme. Let me know if any other issues.
